## tf.random.normal & tf.concat

In [17]:
import tensorflow as tf


a = tf.random.normal((1, 2, 1))
print(a)
b = tf.concat((a, a), axis=1)
print(b)

tf.Tensor(
[[[-0.10222221]
  [-0.02582106]]], shape=(1, 2, 1), dtype=float32)
tf.Tensor(
[[[-0.10222221]
  [-0.02582106]
  [-0.10222221]
  [-0.02582106]]], shape=(1, 4, 1), dtype=float32)


## tf.transpose

In [20]:
c = tf.transpose(a, [1, 0, 2])
print(c)
c = tf.transpose(a, [2, 0, 1])
print(c)

tf.Tensor(
[[[-0.10222221]]

 [[-0.02582106]]], shape=(2, 1, 1), dtype=float32)
tf.Tensor([[[-0.10222221 -0.02582106]]], shape=(1, 1, 2), dtype=float32)


In [24]:
tf.Variable(tf.random.normal([4, 3], stddev=0.1))

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[ 0.0858694 ,  0.12292894,  0.01292848],
       [ 0.04902585,  0.1227443 , -0.1501322 ],
       [-0.1658654 ,  0.01572886, -0.1265556 ],
       [-0.07827426,  0.05712532, -0.08203812]], dtype=float32)>

## tf.tensordot

In [29]:
a = tf.random.normal((2, 3, 4))
print(a)
b = tf.random.normal((4, 5))
print(b)
c = tf.tensordot(a, b, axes=1)
print(c)

tf.Tensor(
[[[-0.41193035  0.26789182 -1.4850671   1.3785921 ]
  [-0.01416892  0.8437764  -0.6722354   1.5075653 ]
  [-0.08367111  0.20505868 -0.2167157  -0.01219765]]

 [[-2.8171031  -0.93070906 -1.0103035  -0.58459383]
  [-0.661697   -0.54233503 -1.1685046   1.3818896 ]
  [-1.0055088   0.7730256  -1.1667318  -0.23853359]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[-1.1642122  -0.5438389   0.42585605 -0.21038017 -0.6888776 ]
 [ 0.65211034  0.94501084  1.013366    0.18263787  0.17209421]
 [ 0.8046385   0.53817683 -0.0487936  -0.12879546  0.38653234]
 [ 0.40791658  0.9856485  -1.4904532  -0.25930944  0.643263  ]], shape=(4, 5), dtype=float32)
tf.Tensor(
[[[ 2.1677803e-02  1.0367630e+00 -1.8862159e+00 -3.0622898e-02
    6.4264303e-01]
  [ 6.4078534e-01  1.9292314e+00 -1.3651344e+00 -1.4725864e-01
    8.6488986e-01]
  [ 5.1778391e-02  1.1063231e-01  2.0092201e-01  8.6129181e-02
    1.3146426e-03]]

 [[ 1.6213863e+00 -4.6740574e-01 -1.2222233e+00  7.0439309e-01
    1.0139071e+00]
  [ 4

## tf.nn.softmax

In [30]:
a = tf.random.normal((1, 2, 3))
print(a)
b = tf.nn.softmax(a)
print(b)

tf.Tensor(
[[[ 1.1523829   0.3964312  -0.37968293]
  [-1.0782012   0.05612426  0.77199376]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[0.59324217 0.2785649  0.12819299]
  [0.09550976 0.29694703 0.60754323]]], shape=(1, 2, 3), dtype=float32)


## tf.reduce_sum

In [35]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = tf.reduce_sum(a, axis=-1)
print(b)

tf.Tensor([ 6 15 24], shape=(3,), dtype=int32)
